# 1. ML methods

Benchmark

Overal Accuracy

1. Logistic Regression: 0.61
2. Random Forest: 0.63
3. Gradient Boosting: 0.61

Uptrend Accuracy

1. Logistic Regression: 0.58
2. Random Forest: 0.61
3. Gradient Boosting: 0.59

Downtrend Accuracy

1. Logistic Regression: 0.66
2. Random Forest: 0.68
3. Gradient Boosting: 0.63


## (0) Before training, Check some numbers


In [ ]:
# Time period
print('Time Period')
print('From:', time_start)
print('To:', time_end, '\n')

# Sample size
print('Sample size:', X.shape[0])
print('Feature:', X.shape[1])
print(X.columns.values, '\n')
print('Target:', y.name, '\n')
print('Train: Test: Val = 0.81: 0.1: 0.09=', X_train.shape[0], X_test.shape[0], X_val.shape[0])

Time Period
From: 2013-01-01T00:00:00
To: 2022-12-31T00:00:00 

Sample size: 2518
Feature: 10
['Today_trend' 'Sma' 'Rsi' 'Kd' 'Ema_12' 'Ema_26' 'Macd'
 'title_sentiment_score' 'title_midterm_sentiment'
 'title_longterm_sentiment'] 

Target: Tomorrow_trend_cate 

Train: Test: Val = 0.81: 0.1: 0.09= 2039 252 227


## (1) Logistic Regression

In [ ]:
model = LogisticRegression(multi_class='multinomial', random_state=42)

pipeline = Pipeline([('scaler', MinMaxScaler()), ('classifier', model)])

# Don't forget. fit doesn't accept string input
pipeline.fit(X_train, y_train)

Pipeline(steps=[('scaler', MinMaxScaler()),
                ('classifier',
                 LogisticRegression(multi_class='multinomial',
                                    random_state=42))])

In [ ]:
# Evaluation

# Accuracy
print('Overall Accuracy:')
score_train = pipeline.score(X_train, y_train)
score_test = pipeline.score(X_test, y_test)
print('Training Accuracy:', score_train)
print('Testing Accuracy:', score_test, '\n')

# Train confusion matrix
y_pred = pipeline.predict(X_train)

print('===========================')
print('Training Result:')
print(classification_report(y_train, y_pred))
print(confusion_matrix(y_train, y_pred), '\n')

# Test confusion matrix
y_pred = pipeline.predict(X_test)

print('===========================')
print('Testing Result:')
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

Overall Accuracy:
Training Accuracy: 0.5463462481608632
Testing Accuracy: 0.5476190476190477 

Training Result:
              precision    recall  f1-score   support

           0       0.52      0.18      0.27       941
           1       0.55      0.86      0.67      1098

    accuracy                           0.55      2039
   macro avg       0.54      0.52      0.47      2039
weighted avg       0.54      0.55      0.49      2039

[[173 768]
 [157 941]] 

Testing Result:
              precision    recall  f1-score   support

           0       0.56      0.16      0.25       118
           1       0.55      0.89      0.68       134

    accuracy                           0.55       252
   macro avg       0.55      0.52      0.46       252
weighted avg       0.55      0.55      0.48       252

[[ 19  99]
 [ 15 119]]


## (2) Random Forest

In [ ]:
model = RandomForestClassifier(random_state=42)
pipeline = Pipeline([('scaler', MinMaxScaler()), ('classifier', model)])

# parameter
param_grid = [
    {'classifier__n_estimators': [50, 100, 500, 1000]},
    {'classifier__max_depth': [1, 5, 10, 25]},
    {'classifier__max_features': [*np.arange(0.1, 1.1, 0.1)]}
]

gridsearch = GridSearchCV(pipeline, param_grid)

gridsearch.fit(X_train, y_train)

GridSearchCV(estimator=Pipeline(steps=[('scaler', MinMaxScaler()),
                                       ('classifier',
                                        RandomForestClassifier(random_state=42))]),
             param_grid=[{'classifier__n_estimators': [50, 100, 500, 1000]},
                         {'classifier__max_depth': [1, 5, 10, 25]},
                         {'classifier__max_features': [0.1, 0.2,
                                                       0.30000000000000004, 0.4,
                                                       0.5, 0.6,
                                                       0.7000000000000001, 0.8,
                                                       0.9, 1.0]}])

In [ ]:
# Evaluation

# Accuracy
print('Overall Accuracy:')
score_train = gridsearch.score(X_train, y_train)
score_test = gridsearch.score(X_test, y_test)
print('Training Accuracy:', score_train)
print('Testing Accuracy:', score_test, '\n')

# Train confusion matrix
y_pred = gridsearch.predict(X_train)

print('===========================')
print('Training Result:')
print(classification_report(y_train, y_pred))
print(confusion_matrix(y_train, y_pred), '\n')

# Test confusion matrix
y_pred = gridsearch.predict(X_test)

print('===========================')
print('Testing Result:')
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

Overall Accuracy:
Training Accuracy: 0.5468366846493379
Testing Accuracy: 0.5515873015873016 

Training Result:
              precision    recall  f1-score   support

           0       0.64      0.04      0.08       941
           1       0.54      0.98      0.70      1098

    accuracy                           0.55      2039
   macro avg       0.59      0.51      0.39      2039
weighted avg       0.59      0.55      0.41      2039

[[  39  902]
 [  22 1076]] 

Testing Result:
              precision    recall  f1-score   support

           0       0.78      0.06      0.11       118
           1       0.54      0.99      0.70       134

    accuracy                           0.55       252
   macro avg       0.66      0.52      0.41       252
weighted avg       0.65      0.55      0.42       252

[[  7 111]
 [  2 132]]


## (3) Gradient Boosting

In [ ]:
# Train
model = GradientBoostingClassifier(random_state=42)
pipeline = Pipeline([('scaler', MinMaxScaler()), ('classifier', model)])

# parameter
param_grid = [
    # {"classifier__learning_rate": [0.01, 0.025, 0.05, 0.075, 0.1, 0.15, 0.2]},
    # {"classifier__min_samples_split": np.linspace(0.1, 0.5, 12)},
    # {"classifier__min_samples_leaf": np.linspace(0.1, 0.5, 12)},
    # {"classifier__max_depth":[3,5,8]},
    # {"classifier__max_features":["log2","sqrt"]},
    # {"classifier__criterion": ["friedman_mse",  "absolute_error"]},
    # {"classifier__subsample":[0.5, 0.618, 0.8, 0.85, 0.9, 0.95, 1.0]},
    {"classifier__n_estimators":[100]}
    ]

gridsearch = GridSearchCV(pipeline, param_grid)

gridsearch.fit(X_train, y_train)

GridSearchCV(estimator=Pipeline(steps=[('scaler', MinMaxScaler()),
                                       ('classifier',
                                        GradientBoostingClassifier(random_state=42))]),
             param_grid=[{'classifier__n_estimators': [100]}])

In [ ]:
# Evaluation

# Accuracy
print('Overall Accuracy:')
score_train = gridsearch.score(X_train, y_train)
score_test = gridsearch.score(X_test, y_test)
print('Training Accuracy:', score_train)
print('Testing Accuracy:', score_test, '\n')

# Train confusion matrix
y_pred = gridsearch.predict(X_train)

print('===========================')
print('Training Result:')
print(classification_report(y_train, y_pred))
print(confusion_matrix(y_train, y_pred), '\n')

# Test confusion matrix
y_pred = gridsearch.predict(X_test)

print('===========================')
print('Testing Result:')
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

Overall Accuracy:
Training Accuracy: 0.7435017165277097
Testing Accuracy: 0.5833333333333334 

Training Result:
              precision    recall  f1-score   support

           0       0.82      0.57      0.67       941
           1       0.71      0.89      0.79      1098

    accuracy                           0.74      2039
   macro avg       0.76      0.73      0.73      2039
weighted avg       0.76      0.74      0.74      2039

[[540 401]
 [122 976]] 

Testing Result:
              precision    recall  f1-score   support

           0       0.58      0.40      0.47       118
           1       0.58      0.75      0.66       134

    accuracy                           0.58       252
   macro avg       0.58      0.57      0.56       252
weighted avg       0.58      0.58      0.57       252

[[ 47  71]
 [ 34 100]]


# 2. Evaluation